### ISSUE TITLE
Getting Error in async_security_handler_factory.py

### ISSUE THREAD

**Issue by ddurham2** [spec-first/connexion#1509]
Concerning: https://github.com/spec-first/connexion/blob/895d3d475aec60d6dbb5d62fdc833895559f32af/connexion/security/async_security_handler_factory.py#L88

It appears that when a security verification function in the server code throws an exception, we get the following error.

```
server  | 20220406 05:42:33.044 172 aiohttp_api:ERROR>Error handling request
server  | Traceback (most recent call last):
server  |   File "/usr/local/lib/python3.8/dist-packages/connexion/apis/aiohttp_api.py", line 55, in problems_middleware
server  |     response = await handler(request)
server  |   File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_middlewares.py", line 110, in impl
server  |     return await handler(request)
server  |   File "/usr/local/lib/python3.8/dist-packages/connexion/decorators/decorator.py", line 55, in wrapper
server  |     connexion_response = await connexion_response
server  |   File "/usr/local/lib/python3.8/dist-packages/connexion/security/async_security_handler_factory.py", line 88, in wrapper
server  |     request.context['user'] = token_info.get('sub', token_info.get('uid'))
server  | AttributeError: 'coroutine' object has no attribute 'get'
```

If that make instance sense, then FYI, else I'll try to repro specifically.

**Comment by Ruwann** [comment]
Hi @ddurham2 , thanks for the report. The exception from the security verification function should be propagated further.
Are you on the latest version of connexion and does it occur as well on version 2.12? If so, it might be a regression introduced by #1474

**Comment by ddurham2** [comment]
It's happening in 2.13 for me.  I can check back the last two releases if you like.  I'm pretty sure prior to 2.12 it was not happening as this is a changed result in my unit test, and it looks like the whole file is pretty new.

**Comment by Ruwann** [comment]
Alright, thanks for checking! It would be great if you have a reproducible example.
Just the line where the exception is thrown in the security function and the corresponding OpenAPI security scheme could already be enough to start with.

**Comment by RobbeSneyders** [comment]
In the code below, if an error is thrown in the line `token_info = await token_info`, the loop can be exited with `token_info` still being a coroutine, preventing the `if token_info is cls.no_value:` block from being triggered.

https://github.com/spec-first/connexion/blob/895d3d475aec60d6dbb5d62fdc833895559f32af/connexion/security/async_security_handler_factory.py#L68-L88

I think we can solve it by adding `token_info = cls.no_value` in the `except` block.

**Comment by RobbeSneyders** [comment]
Or replace the `token_info = cls.no_value` with an `else` block from the for loop.

**Comment by ddurham2** [comment]
I take it that the problem is well understood enough that I don't need to create an example?

**Comment by RobbeSneyders** [comment]
This is released in 2.13.1
