### ISSUE TITLE
[3.0.0a2] connexion example not working

### ISSUE THREAD

**Issue by drummerwolli** [spec-first/connexion#1670]
### Description

I'm setting up a new connexion project, and i want to directly use version 3.0.0 to not have later a costly migration. so for now, its okay to use a non-production version. But I get an import error. so i checked the most basic example, but i still get the same error.

### Expected behaviour

the example project just works with the latest 3.0.0 alpha version.

### Actual behaviour

I get an import error:

```
Traceback (most recent call last):
  File "/home/fhalkivaha/GIT/connexion-example/app.py", line 52, in <module>
    app.run(port=8080, server='gevent')
  File "/home/fhalkivaha/.pyenv/versions/3.10.6/envs/venv-3.10-1/lib/python3.10/site-packages/connexion/apps/abstract.py", line 243, in run
    self.middleware.run(import_string, **kwargs)
  File "/home/fhalkivaha/.pyenv/versions/3.10.6/envs/venv-3.10-1/lib/python3.10/site-packages/connexion/middleware/main.py", line 324, in run
    uvicorn.run(app, **kwargs)
  File "/home/fhalkivaha/.pyenv/versions/3.10.6/envs/venv-3.10-1/lib/python3.10/site-packages/uvicorn/main.py", line 445, in run
    config = Config(app, **kwargs)
TypeError: Config.__init__() got an unexpected keyword argument 'server'
```

### Steps to reproduce

1. `git clone git@github.com:hjacobs/connexion-example.git`
2. `cd connexion-example`
3. `rm Pipfile && rm Pipfile.lock` (we gonna use `poetry`)
4. add this basic poetry file (created with `poetry init`):

```
[tool.poetry]
name = "connexion-example"
version = "0.1.0"
description = ""
authors = ["fhalkivaha <fabian@zalando.de>"]
readme = "README.md"
packages = [{include = "connexion_example"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

5. `poetry add connexion --allow-prereleases -E flask -E uvicorn`
6. `poetry run python3 app.py`

### Additional info:

I'm using poetry version 1.4.0.

Output of the commands:

- `poetry run python3 --version : Python 3.10.6`
- connexion commit used: cd64611

**Comment by drummerwolli** [comment]
i just saw that https://github.com/spec-first/connexion/pull/1648 was merged just two weeks ago, and i would need that. so even more a reason to use 3.0.0 :partying_face:

**Comment by RobbeSneyders** [comment]
Hi @drummerwolli,

```
ModuleNotFoundError: Please install connexion using the 'flask' extra
```

Can you try:
```
pip install --pre connexion[flask]
```

**Comment by drummerwolli** [comment]
i'm using poetry, so cant use pip. but i found now finally the flag for poetry to install pre-packages: `poetry add connexion --allow-prereleases --extras "flask"`

but now i get a different import error:

```
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
```

 (adjusted my comment above)

**Comment by RobbeSneyders** [comment]
There's also an extra for `uvicorn`, but we should make the error more clear.

**Comment by drummerwolli** [comment]
yeah, also just saw that. i added now the uvicorn package: `poetry add connexion --allow-prereleases -E flask -E uvicorn`

but now i get:

```
Traceback (most recent call last):
  File "/home/fhalkivaha/GIT/connexion-example/app.py", line 52, in <module>
    app.run(port=8080, server='gevent')
  File "/home/fhalkivaha/.pyenv/versions/3.10.6/envs/venv-3.10-1/lib/python3.10/site-packages/connexion/apps/abstract.py", line 243, in run
    self.middleware.run(import_string, **kwargs)
  File "/home/fhalkivaha/.pyenv/versions/3.10.6/envs/venv-3.10-1/lib/python3.10/site-packages/connexion/middleware/main.py", line 324, in run
    uvicorn.run(app, **kwargs)
  File "/home/fhalkivaha/.pyenv/versions/3.10.6/envs/venv-3.10-1/lib/python3.10/site-packages/uvicorn/main.py", line 445, in run
    config = Config(app, **kwargs)
TypeError: Config.__init__() got an unexpected keyword argument 'server'
```

**Comment by RobbeSneyders** [comment]
`uvicorn` does not accept a `server` keyword.

**Comment by drummerwolli** [comment]
ah, i see now the server key argument in the app.run. removing that works just fine! thanks :heart:
