### PR TITLE
Update sqlalchemy example to work with Python 3.8, 3.9 and 3.10

### PR DESCRIPTION
**Pull request by ifeLawal**
When trying to work with this example I received the error:
```bash
AttributeError: module 'datetime' has no attribute 'UTC'
```

Doing some research, it seems the new pattern is to pull UTC from timezone. Making the suggested edit as a PR

Fixes # .

Changes proposed in this pull request:

 -
 -
 -

### CODE REVIEW

**Comment by chrisinmtown** [comment]
Thanks for using my example! What version of Python are you using to run it? I'm using Python 3.13 and when I clone your repo, checkout your branch and run the example, I see this error:
```
INFO:root:Creating pet 1..
Traceback (most recent call last):
  File "/Users/me/git/github/connexion-ifelawal/examples/sqlalchemy/app.py", line 59, in <module>
    put_pet(id_, pet)
    ~~~~~~~^^^^^^^^^^
  File "/Users/me/git/github/connexion-ifelawal/examples/sqlalchemy/app.py", line 33, in put_pet
    pet["created"] = datetime.datetime.now(timezone.UTC)
                                           ^^^^^^^^^^^^
AttributeError: type object 'datetime.timezone' has no attribute 'UTC'. Did you mean: 'utc'?
```

In recent Python versions the `datetime` package has a `UTC` constant as an alias for `datetime.timezone.utc` according to https://docs.python.org/3/library/datetime.html. It was added in 2022 in this PR: https://github.com/python/cpython/issues/91928

Still you have definitely caught something that might block running the example in old(er) versions of Python.  I recommend updating your PR to have the following:
```
% git diff app.py 
diff --git a/examples/sqlalchemy/app.py b/examples/sqlalchemy/app.py
index 7d04bc6..9797c80 100644
--- a/examples/sqlalchemy/app.py
+++ b/examples/sqlalchemy/app.py
@@ -1,5 +1,5 @@
-import datetime
 import logging
+from datetime import datetime, timezone
 
 import connexion
 import orm
@@ -29,7 +29,7 @@ def put_pet(pet_id, pet):
             p.update(**pet)
         else:
             logging.info("Creating pet %s..", pet_id)
-            pet["created"] = datetime.datetime.now(datetime.UTC)
+            pet["created"] = datetime.now(timezone.utc)
             db_session.add(orm.Pet(**pet))
         db_session.commit()
         return NoContent, (200 if p is not None else 201)
```

**Comment by ifeLawal** [comment]
Good catch! Appreciate the python links.

I was on Python 3.9.7 for my run of the example, an old(er) Python version that is not current. I updated the commit to match your diff for the PR.

**Comment by chrisinmtown** [comment]
I finally learned how to supply the appropriate arguments to `isort` to check examples. Unfortunately it is still not happy with your branch, a blank line is missing:
```
% isort --thirdparty connexion --check-only --diff app.py
ERROR: /Users/me/git/github/connexion-ifelawal/examples/sqlalchemy/app.py Imports are incorrectly sorted and/or formatted.
--- /Users/me/git/github/connexion-ifelawal/examples/sqlalchemy/app.py:before	2025-01-05 07:25:57.485152
+++ /Users/me/git/github/connexion-ifelawal/examples/sqlalchemy/app.py:after	2025-01-05 07:27:50.626244
@@ -3,6 +3,7 @@
 
 import orm
 from connexion import FlaskApp, NoContent
+
 
 def get_pets(limit, animal_type=None):
     with db_session_factory() as db_session:
```
I created a Python 3.9 venv to run your code, but the example still fails with the same error as before. Does this work for you?
```
% python3.9 app.py
INFO:root:Creating pet 1..
Traceback (most recent call last):
  File "/Users/me/git/github/connexion-ifelawal/examples/sqlalchemy/app.py", line 56, in <module>
    put_pet(id_, pet)
  File "/Users/me/git/github/connexion-ifelawal/examples/sqlalchemy/app.py", line 30, in put_pet
    pet["created"] = datetime.now(timezone.UTC)
AttributeError: type object 'datetime.timezone' has no attribute 'UTC'
```

**Comment by ifeLawal** [comment]
Appreciate the diffs! I did a test with the lowercase `timezone.utc` on my local and that worked. Updated the spacing and the utc casing

**Comment by chrisinmtown** [comment]
Cool. You might want to update the first line of the commit message to be a bit more descriptive, I recommend something like this:

    Update sqlalchemy example to work with Python 3.8, 3.9 and 3.10

**Comment by chrisinmtown** [comment]
+1 from me - but I'm not a maintainer so it doesn't really count lol

**Comment by ifeLawal** [comment]
@chrisinmtown appreciate the help in getting this ready. You gave maintainer status.

Any thoughts on a maintainer to bring this to for review/approval?

File: examples/sqlalchemy/app.py [hunk 1]
```diff
@@ -1,9 +1,8 @@
-import datetime
 import logging
+from datetime import datetime, timezone
 
-import connexion
 import orm
-from connexion import NoContent
+from connexion import FlaskApp, NoContent
```
Comment (Ruwann) [inline examples/sqlalchemy/app.py:5]:
```suggestion
from connexion import NoContent
```

File: examples/sqlalchemy/app.py [hunk 2]
```diff
@@ -56,7 +55,7 @@ def delete_pet(pet_id):
 }
 for id_, pet in pets.items():
     put_pet(id_, pet)
-app = connexion.FlaskApp(__name__, specification_dir="spec")
+app = FlaskApp(__name__, specification_dir="spec")
```
Comment (Ruwann) [inline examples/sqlalchemy/app.py:58]:
```suggestion
app = connexion.FlaskApp(__name__, specification_dir="spec")
```

File: examples/sqlalchemy/app.py [hunk 3]
```diff
@@ -1,9 +1,8 @@
-import datetime
 import logging
+from datetime import datetime, timezone
```
Comment (Ruwann) [inline examples/sqlalchemy/app.py:3]:
```suggestion

import connexion
```

**Review by Ruwann — APPROVED** [review]
Thanks for the PR!

To keep the examples consistent, let's keep the `connexion.FlaskApp` style
